sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Pooley68/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Pooley68/docker-react npm run test
